/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.buw.se4de;




import com.google.common.collect.ArrayListMultimap;
import com.google.common.collect.Multimap;
import java.util.Collection;


public class App {

	public static void main(String[] args) {
		
		new OnlineTest("Online Test Of Java");
		
	}
	
	
}
